### PR TITLE
Installation steps on Lumen

### PR DESCRIPTION
**Pull request by gmsantos**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I'm not convinced this extra info is needed. It's not included in any of the other laravel packages here.

**Comment by taylorotwell** [comment]
Closing for now.

**Comment by gmsantos** [comment]
@GrahamCampbell @taylorotwell my intention is to make clear that tinker is also compatible with Lumen. I had this doubt at first and maybe others will ask themselves that too.

Any toughs? Maybe a note on lumen docs or a composer.json sugestions on laravel/lumen

**Comment by GrahamCampbell** [comment]
The composer.json already says it's compatible with lumen because it doesn't require laravel/framework, only some components.

**Pull request closed without merging**
