### PR TITLE
[2.x] Allow psy/psysh 0.10.x

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by driesvints** [comment]
Can't we just upgrade to 0.10?

**Comment by GrahamCampbell** [comment]
No harm in allowing both versions so that we don't conflict with global installs.

**Comment by andreladocruz** [comment]
@GrahamCampbell have you tested v0.11.1 version too?

**Comment by driesvints** [comment]
@andreladocruz I'll take a look on Monday to add support for that.

**Comment by andreladocruz** [comment]
@driesvints, thanks!!! =)

**Pull request merged**
